### ISSUE TITLE
Rotel Player is not available

### ISSUE THREAD

**Issue by nirvine** [matthijs-oosterhoff/homeassistant_rotel#8]
I would love to use this component for manage my Rotel A14.
I have the amp plugged into the Rpi running Home Assistant (in Docker - Supervised version), via an RS232 - USB cable. 
After copying the files to the custom_components directory and rebooting the RPi, I get the following error:
 
Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:361
integration: Media player (documentation, issues)
First occurred: 10:13:29 AM (1 occurrences)
Last logged: 10:13:29 AM

Error while setting up roteltcp platform for media_player
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/roteltcp/media_player.py", line 61, in async_setup_platform
    await rotel.start(hass)
  File "/config/custom_components/roteltcp/media_player.py", line 82, in start
    transport, protocol = await hass.loop.create_connection(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.20.36', 9590)

How can I fix this?

**Comment by nirvine** [comment]
Screenshot of the entity:
![image](https://github.com/user-attachments/assets/4cd56645-731b-41d4-8554-d86d17b21870)

**Comment by matthijs-oosterhoff** [comment]
Hi @nirvine! I didn't see this issue earlier, I just found out I didn't setup notifications for this repository.

Are you still running into this issue? I would be happy to help but I'm not sure about your setup. You are connecting to the receiver using an RS232 cable. This plugin assumes you are connecting through TCP, using the network interface on your receiver, assuming that's available.

I suppose it may work if you setup a TCP -> RS232 proxy on your Raspberry Pi, have you done anything like that?

**Comment by nirvine** [comment]
I had not heard of a TCP->RS232 proxy, but will look into it. I tried using an alternative solution (a docker repo for Rotel) but I cannot use that with HAOS.

**Comment by nirvine** [comment]
I just realised that it will not work for me, as I also need to be able to switch Speakers A and B off and on.

**Comment by matthijs-oosterhoff** [comment]
@nirvine I might be able to add that to the Home Assistant component. Switching speakers A and B are defined in the Rotel protocol as `speaker_a!` and `speaker_b!`. That's easy to add. I'm willing to put some time in implementing that but only if I'm sure you'll be using it ;)

So did you get it working yet? I'm not really sure why you actually want to connect using RS232, since the A14 has a dedicated Ethernet port. Why not just use that?

**Comment by nirvine** [comment]
Thank you for considering adding speakers. 
The Rotel is at a ski lodge , 6 hours drive away from me. and I have the RS232 cable plugged in. The last time I tried connecting the ethernet cable, everything stopped working so I took it out. People are using it, and I cannot risk breaking things until the end of the ski season (southern hemisphere).
Hopefully it will go smoothly in November when I can test things in peace.

**Comment by nirvine** [comment]
I have now connected the ethernet cable, and I can see the Rotel in Home Assistant. 
When I used the power button for the entity, the device became unavailable. The amp is showing that the power is off, but I cannot manually turn it back on. 

<img width="566" height="420" alt="Image" src="https://github.com/user-attachments/assets/b3cf6c69-c78a-49e8-beaa-e49a308b64b3" />

The error message is: 

> This error originated from a custom integration.
> 
> Logger: custom_components.roteltcp.media_player
> Source: custom_components/roteltcp/media_player.py:271
> integration: roteltcp (documentation)
> First occurred: 10:28:14 AM (1 occurrence)
> Last logged: 10:28:14 AM
> 
> ROTEL: Connection lost !
> 

Edit: The  power button was showing a red light on the amp.  I removed the entry from configuration.yaml, and the amp power button is now working normally. 
Another log entry is:

> This error originated from a custom integration.
> 
> Logger: custom_components.roteltcp.media_player
> Source: custom_components/roteltcp/media_player.py:105
> integration: RotelTCP (documentation)
> First occurred: 10:29:04 AM (203 occurrences)
> Last logged: 10:51:11 AM
> 
> ROTEL: Connection failed ([Errno 113] Connect call failed ('192.168.0.202', 9590)), retrying in 10s...

**Comment by matthijs-oosterhoff** [comment]
Maybe your rotel amp behaves differently when powering off. Possibly the rotel shuts down its network connection too.

Can you ping the rotel amp on that IP? And if that works, can you verify if you can still connect to the port? For example using ping and/or telnet.

A successful result looks like this, (make sure to replace the IP):

```
root@nas:~# ping -c 2 192.168.86.109
PING 192.168.86.109 (192.168.86.109) 56(84) bytes of data.
64 bytes from 192.168.86.109: icmp_seq=1 ttl=254 time=0.749 ms
64 bytes from 192.168.86.109: icmp_seq=2 ttl=254 time=1.96 ms

--- 192.168.86.109 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1009ms
rtt min/avg/max/mdev = 0.749/1.352/1.956/0.603 ms
```

```
root@nas:~# telnet 192.168.86.109 9590
Trying 192.168.86.109...
Connected to 192.168.86.109.
Escape character is '^]'.
model=RC-1572$power=standby$
```


If that doesn't work, you should check if your amp has some (possibly well hidden) setting to keep the network connection active when powered off, or at least in standby.
